version: '3.1'

services:
    web:
        container_name: portalnoticias
        image: python:3.6
        volumes:
            - .:/home/application/current
        working_dir: /home/application/current
        ports:
            - "5000:5000"
        depends_on:
            - db
        command: tail -f /dev/null

    db:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: 'portalnoticias'
            POSTGRES_USER: 'portalnoticias'
            POSTGRES_PASSWORD: 'db_password'

    adminer:
        image: adminer
        # restart: always
        ports:
            - "8081:8080"
