"""empty message

Revision ID: 2366e3ec7dd3
Revises: d1d72dd434ea
Create Date: 2020-08-18 14:09:04.514112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2366e3ec7dd3'
down_revision = 'd1d72dd434ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('slug', sa.String(length=512), nullable=True))
    op.add_column('noticias', sa.Column('subtitulo', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'noticias', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noticias', type_='unique')
    op.drop_column('noticias', 'subtitulo')
    op.drop_column('noticias', 'slug')
    # ### end Alembic commands ###
