"""empty message

Revision ID: d1d72dd434ea
Revises: fec54f7d3481
Create Date: 2020-07-28 05:43:49.252154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d72dd434ea'
down_revision = 'fec54f7d3481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('slug', sa.String(length=100), nullable=False, server_default=' '))
    op.create_unique_constraint(None, 'categorias', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias', type_='unique')
    op.drop_column('categorias', 'slug')
    # ### end Alembic commands ###
